### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by hatkidchan** [hatkidchan/yaitaa#2]
**TODO**: add `test` target to `Makefile`, as well as test scripts (in Python, Bash or even in C itself?).

Test scripts should download sample images from this issue (***TODO**: add images*) into `obj/` folder.

Test scripts should run after running `testbuild` target or as last step of it. Test scripts should depend on `all` target.

`help wanted` label is set, because I need some sample images, if possible. SFW-only, public domain and/or royalty-free only. Self-made content also allowed. Images should be in either PNG or BMP (i.e. lossless compression only) to reduce ambiguity caused by (de-)compression.

**Comment by hatkidchan** [comment]
Test cases should include, but not limit to:
 - [ ] Testing for valid JSON in `-F json`
 - [ ] Testing for correct width/height in `-F json`
 - [ ] Testing for correct pixel values
 - [ ] Testing for hanging color after `-F ansi`
 - [ ] Testing for valid table structure in `-F html`
 - [ ] Testing for valid palette conversion
 
***TODO**: more test cases*
